### ISSUE TITLE
Current HEAD fails initialization

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#110]
Using the patroni-compose project (https://github.com/pgexperts/patroni-compose):

dbnode1_1 | scope: &scope testcluster
dbnode1_1 | ttl: &ttl 30
dbnode1_1 | loop_wait: &loop_wait 10
dbnode1_1 | restapi:
dbnode1_1 |   listen: 172.17.0.12:8001
dbnode1_1 |   connect_address: 172.17.0.12:8001
dbnode1_1 |   auth: 'admin:admin'
dbnode1_1 |   certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
dbnode1_1 |   keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
dbnode1_1 | etcd:
dbnode1_1 |   scope: *scope
dbnode1_1 |   ttl: *ttl
dbnode1_1 |   host: etcd:2379
dbnode1_1 | postgresql:
dbnode1_1 |   name: dbnode1
dbnode1_1 |   scope: *scope
dbnode1_1 |   listen: 0.0.0.0:5432
dbnode1_1 |   connect_address: 172.17.0.12:5432
dbnode1_1 |   data_dir: /pgdata/data
dbnode1_1 |   maximum_lag_on_failover: 10485760 # 10 megabyte in bytes
dbnode1_1 |   use_slots: True
dbnode1_1 |   pgpass: /tmp/pgpass0
dbnode1_1 |   create_replica_method: basebackup
dbnode1_1 |   pg_hba:
dbnode1_1 |   - local all all  trust
dbnode1_1 |   - host all all 0.0.0.0/0 md5
dbnode1_1 |   - hostssl all all 0.0.0.0/0 md5
dbnode1_1 |   replication:
dbnode1_1 |     username: replicator
dbnode1_1 |     password: replicate
dbnode1_1 |     network:  172.17.0.12/16
dbnode1_1 |   superuser:
dbnode1_1 |     username: patroni
dbnode1_1 |     password: super
dbnode1_1 |   admin:
dbnode1_1 |     username: admin
dbnode1_1 |     password: admin
dbnode1_1 |   parameters:
dbnode1_1 |     archive_mode: "off"
dbnode1_1 |     archive_command: mkdir -p ../wal_archive && cp %p ../wal_archive/%f
dbnode1_1 |     wal_level: hot_standby
dbnode1_1 |     max_wal_senders: 10
dbnode1_1 |     hot_standby: "on"
dbnode1_1 |     max_replication_slots: 7
etcd_1    | 2015-12-10 21:32:29.231848 I | raft: ce2a822cea30bfca is starting a new election at term 1
etcd_1    | 2015-12-10 21:32:29.232039 I | raft: ce2a822cea30bfca became candidate at term 2
etcd_1    | 2015-12-10 21:32:29.232325 I | raft: ce2a822cea30bfca received vote from ce2a822cea30bfca at term 2
etcd_1    | 2015-12-10 21:32:29.232492 I | raft: ce2a822cea30bfca became leader at term 2
etcd_1    | 2015-12-10 21:32:29.232682 I | raft: raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 2
etcd_1    | 2015-12-10 21:32:29.233238 I | etcdserver: published {Name:default ClientURLs:[http://0.0.0.0:2379 http://0.0.0.0:4001]} to cluster 7e27652122e8b2ae
etcd_1    | 2015-12-10 21:32:29.233343 I | etcdserver: setting up the initial cluster version to 2.2
etcd_1    | 2015-12-10 21:32:29.238663 N | etcdserver: set the initial cluster version to 2.2
dbnode1_1 | 2015-12-10 21:32:29,346 INFO: Starting new HTTP connection (1): 172.17.0.11
dbnode1_1 | 2015-12-10 21:32:29,354 INFO: removing initialize key after failed attempt to initialize the cluster
dbnode1_1 | 2015-12-10 21:32:29,375 INFO: renaming data directory to /pgdata/data_2015-12-10-21-32-29
dbnode1_1 | Traceback (most recent call last):
dbnode1_1 |   File "/patroni/patroni.py", line 6, in <module>
dbnode1_1 |     main()
dbnode1_1 |   File "/patroni/patroni/__init__.py", line 73, in main
dbnode1_1 |     patroni.run()
dbnode1_1 |   File "/patroni/patroni/__init__.py", line 54, in run
dbnode1_1 |     logger.info(self.ha.run_cycle())
dbnode1_1 |   File "/patroni/patroni/ha.py", line 439, in run_cycle
dbnode1_1 |     return self._run_cycle()
dbnode1_1 |   File "/patroni/patroni/ha.py", line 405, in _run_cycle
dbnode1_1 |     return self.bootstrap()  # new node
dbnode1_1 |   File "/patroni/patroni/ha.py", line 80, in bootstrap
dbnode1_1 |     self.state_handler.bootstrap()
dbnode1_1 |   File "/patroni/patroni/postgresql.py", line 672, in bootstrap
dbnode1_1 |     ret = self.initialize() and self.start()
dbnode1_1 |   File "/patroni/patroni/postgresql.py", line 201, in initialize
dbnode1_1 |     ret = subprocess.call(self._pg_ctl + ['initdb'] + ['-o', ' '.join(options)] if options else []) == 0
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 522, in call
dbnode1_1 |     return Popen(*popenargs, **kwargs).wait()
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
dbnode1_1 |     errread, errwrite)
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 1206, in _execute_child
dbnode1_1 |     executable = args[0]
dbnode1_1 | IndexError: list index out of range
patronicompose_dbnode1_1 exited with code 1

**Comment by jberkus** [comment]
Investigating possible causes.

**Comment by alexeyklyukin** [comment]
I think the problem is in the recently added initdb configuration clause, which allows to specify initdb options... I will check what happens if it's missing.

**Comment by alexeyklyukin** [comment]
Should be fixed in https://github.com/zalando/patroni/pull/111

**Comment by jberkus** [comment]
Re-opening, issue is not fixed.

Here's more output from patroni-compose.  What you see here is a replica failing to start up because of a subprocess failure to open a file.  The error output does not tell us what file it is, unfortunately.

dbnode1_1 | 2015-12-23 18:39:06,251 ERROR: Error creating replica using method u: [Errno 2] No such file or directory
dbnode1_1 | Traceback (most recent call last):
dbnode1_1 |   File "/patroni/patroni/postgresql.py", line 274, in create_replica
dbnode1_1 |     ret = subprocess.call(shlex.split(cmd) + params, env=env)
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 522, in call
dbnode1_1 |     return Popen(*popenargs, **kwargs).wait()
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
dbnode1_1 |     errread, errwrite)
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
dbnode1_1 |     raise child_exception
dbnode1_1 | OSError: [Errno 2] No such file or directory
dbnode1_1 | 2015-12-23 18:39:06,255 ERROR: Error creating replica using method p: [Errno 2] No such file or directory
dbnode1_1 | Traceback (most recent call last):
dbnode1_1 |   File "/patroni/patroni/postgresql.py", line 274, in create_replica
dbnode1_1 |     ret = subprocess.call(shlex.split(cmd) + params, env=env)
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 522, in call
dbnode1_1 |     return Popen(*popenargs, **kwargs).wait()
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
dbnode1_1 |     errread, errwrite)
dbnode1_1 |   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
dbnode1_1 |     raise child_exception
dbnode1_1 | OSError: [Errno 2] No such file or directory
dbnode1_1 | 2015-12-23 18:39:06,260 INFO: Removing data directory: /pgdata/data
dbnode1_1 | 2015-12-23 18:39:06,260 ERROR: failed to bootstrap from leader

**Comment by jberkus** [comment]
Per this message:

dbnode1_1 | 2015-12-23 18:39:06,255 ERROR: Error creating replica using method p: [Errno 2] No such file or directory

... it looks to me like, despite the configured method for launching replicas being "basebackup", it's ignoring that and looking for a file named "", which of course fails.  Investigating.

**Comment by alexeyklyukin** [comment]
Different issue here, replica_creation_method expects an array of values:
```
replica_creation_method:
    - basebackup
    - wal-e
```

**Comment by jberkus** [comment]
Aha, ok.

We need some way to document changes to the config file format.  You guys keep springing changes on me which I don't know about; the changes are generally good, but we need to have an information flow so that I can update my testing setup.  Ideas on how?

**Comment by alexeyklyukin** [comment]
Yeah, I agree we have to do better on a changelog for new releases. Basically, the master is a moving target, but releases should be immutable, with clearly written changelog and can be used for testing/production. We'll follow this for the next release. Meanwhile, I'll go through the docs to see what we are missing there.
