### ISSUE TITLE
Failover bug when falling back to DCS

### ISSUE THREAD

**Issue by valer-cara** [zalando/patroni#1739]
**Describe the bug**
Error occurring [here](https://github.com/zalando/patroni/blob/e8e87bf0a14b5a85e3ea0b405d2f77003e22f7ad/patroni/ctl.py#L735) `UnboundLocalError: local variable 'scheduled_at' referenced before assignment`

Replacing that with `None` or some other meaningful value fixes the issue.

**To Reproduce**
Happens in k8s, possibly specific to my setup, but I think the code can be inspected to determine that indeed on that path `scheduled_at` is not set

**Expected behavior**
Failover would run smoothly

**Screenshots**
```
root@core-pg-2:/home/postgres# patronictl -c postgres.yml failover --force --candidate core-pg-0             
Current cluster topology                                                                                     
+---------+-----------+-----------------+------+--------------+----+-----------+                             
| Cluster |   Member  |       Host      | Role |    State     | TL | Lag in MB |                             
+---------+-----------+-----------------+------+--------------+----+-----------+                             
| core-pg | core-pg-0 | 100.122.253.198 |      |   running    | 15 |       192 |                             
| core-pg | core-pg-1 | 100.102.130.198 |      | start failed |    |   unknown |                             
| core-pg | core-pg-2 |  100.114.240.70 |      |   stopped    |    |   unknown |                             
+---------+-----------+-----------------+------+--------------+----+-----------+                             
2020-10-22 12:51:53,531 - ERROR - None                                                                       
Traceback (most recent call last):                                                                           
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 658, in _do_failover_or_switchover      
    r = request_patroni(member, 'post', action, failover_value, auth_header(obj))                            
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 160, in request_patroni                 
    verify=verify)                                                                                           
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post                                   
    return request('post', url, data=data, json=json, **kwargs)                                              
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request                                 
    return session.request(method=method, url=url, **kwargs)                                                 
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request                           
    resp = self.send(prep, **send_kwargs)                                                                    
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 624, in send                              
    adapter = self.get_adapter(url=request.url)                                                              
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 715, in get_adapter                       
    raise InvalidSchema("No connection adapters were found for '%s'" % url)                                  
requests.exceptions.InvalidSchema: No connection adapters were found for 'b''://b''/failover'                
2020-10-22 12:51:53,531 - WARNING - Failing over to DCS                                                      
2020-10-22 12:51:53.53178 Could not failover using Patroni api, falling back to DCS                          
Traceback (most recent call last):                                                                           
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 658, in _do_failover_or_switchover      
    r = request_patroni(member, 'post', action, failover_value, auth_header(obj))                            
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 160, in request_patroni                 
    verify=verify)                                                                                           
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post                                   
    return request('post', url, data=data, json=json, **kwargs)                                              
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request                                 
    return session.request(method=method, url=url, **kwargs)                                                 
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request                           
    resp = self.send(prep, **send_kwargs)                                                                    
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 624, in send                              
    adapter = self.get_adapter(url=request.url)                                                              
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 715, in get_adapter                       
    raise InvalidSchema("No connection adapters were found for '%s'" % url)                                  
requests.exceptions.InvalidSchema: No connection adapters were found for 'b''://b''/failover'                
                                                                                                             
During handling of the above exception, another exception occurred:                                          
                                                                                                             
Traceback (most recent call last):                                                                           
  File "/usr/local/bin/patronictl", line 11, in <module>                                                     
    sys.exit(ctl())                                                                                          
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__                                 
    return self.main(*args, **kwargs)                                                                        
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main                                     
    rv = self.invoke(ctx)                                                                                    
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke                                  
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                  
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke                                   
    return ctx.invoke(self.callback, **ctx.params)                                                           
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke                                   
    return callback(*args, **kwargs)                                                                         
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func                            
    return f(get_current_context().obj, *args, **kwargs)                                                     
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 689, in failover                        
    _do_failover_or_switchover(obj, action, cluster_name, master, candidate, force)                          
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 676, in _do_failover_or_switchover      
    dcs.manual_failover(master, candidate, scheduled_at=scheduled_at)                                        
UnboundLocalError: local variable 'scheduled_at' referenced before assignment                                

```

**Environment**
- Patroni version:
patronictl version 1.5.5
- PostgreSQL version: 11
- DCS (and its version): k8s 1.11 [old, yes, but shouldn't matter i believe]

**Patroni configuration file**
n/a

**patronictl show-config**
n/a

**Have you checked Patroni logs?**
yes, but unrelated

**Have you checked PostgreSQL logs?**
yes, but unrelated

**Have you tried to use GitHub issue search?**
found none in a quick search

**Additional context**
n/a

**Comment by CyberDem0n** [comment]
1.5.5 was released more than 1.5 years ago. Since that a lot of bugs have been fixed. Please upgrade to 2.0.1.

Also, all replicas in your cluster are unhealthy.

**Comment by valer-cara** [comment]
Indeed. I have only created the issue after checking that the code in the exception handler linked above hadn't changed since, and thought that it might still happen. This ticket can be closed nevertheless.

Sorry for the lack of context/reproduce instructions, that's a cluster that will soon go away, which I had to failover and that is when I noticed the bug. Thanks for all the work on Patroni!
