### ISSUE TITLE
standby cluster won't stream only restore_command working

### ISSUE THREAD

**Issue by gspiegelberg-pivotal** [zalando/patroni#1855]
Versions:
PostgreSQL 11.7, Patroni 1.6.4, pgbackrest 2.23, etcd 3.3.11, CentOS 7.8

Brief database setup in lab mimicking a production environment:

1. Site 1 has database hosts s81, s82, s83 using synchronous "ANY 1" replication, all good here
2. Site 1 has own etcd cluster and s81, s82 and s83 are only hosts in Patroni cluster
3. Site 1 pg_hba configured to permit replication from site 2 hosts
4. Site 2 has database hosts s84 and s85 with intent to use asynchronous replication from Site 1 s83 to s84 and stream from s84 to s85
5. Site 2 has own etcd cluster and s84 and s85 are only hosts in Patroni cluster
6. Site 2 is standby cluster / replicas only

s84 and s85 only get configured with restore_command in recovery.conf.  Nothing I have done changes that to include primary_conninfo.  Site 2 s85 patroni.yml and recovery.conf below.

I'm certain this is a configuration issue on my part so hopefully a quick open & shut case.

Let me know if more info needed.

Thanks
-Greg

Site 2 s84 recovery. conf:
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
recovery_target_timeline = 'latest'
standby_mode = 'on'
```

patroni.yml on s84 where 10.10.1.83 is site 1 s83 host:
```
scope: pgtest
name: s84

restapi:
  listen: 10.10.1.84:8008
  connect_address: 10.10.1.84:8008

log:
  dir: /var/lib/pgsql/patroni/log
  file_num: 8
  file_size: 1024000

etcd:
  hosts: 10.10.1.84:2379,10.10.1.85:2379,10.10.1.86:2379
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout : 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
    standby_cluster:
      host: 10.10.1.83
      port: 6432
      create_replica_methods:
        - basebackup

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host all         all        127.0.0.1/32  md5
  - host all         all        10.10.1.0/24   md5
  - host replication repuser 10.10.1.81/32  md5
  - host replication repuser 10.10.1.82/32  md5
  - host replication repuser 10.10.1.83/32  md5
  - host replication repuser 10.10.1.84/32  md5
  - host replication repuser 10.10.1.85/32  md5

postgresql:
  listen: 10.10.1.84:6432
  connect_address: 10.10.1.84:6432
  data_dir: /pgdata/11
  bin_dir: /usr/bin
  authentication:
    replication:
      username: repuser
      password: repuser
    superuser:
      username: postgres
      password: postgres
  parameters:
    unix_socket_directories: '/var/run/postgresql, /tmp'
    port: 6432
    wal_level: logical
  create_replica_methods:
    basebackup:
      - verbose
      - max-rate: '100M'
      - checkpoint: 'fast'

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: true
  clonefrom: true
  noloadbalance: true
  replicatefrom: 10.10.1.83
  nosync: true
```

**Comment by CyberDem0n** [comment]
@gspiegelberg-pivotal the `tags` section is completely broken. If the second config has the same values none of the nodes of the standby cluster will stream from the Site 1.

Standby cluster does exactly the same procedures to ensure that there is only one leader and only the standby leader will stream from the Site 1 (https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster). Since tags.nofailover is set to true, it will never become the leader. The `tags.replicatefrom` is also wrong, it should contain the node name, that exists in a given cluster, while you specified the IP which belongs to the cluster from the site1, so effectively it does nothing.
The standby cluster using the content of the `standby_cluster` section stored in DCS. You can see and change it with `patronictl edit-config`.

**Comment by gspiegelberg-pivotal** [comment]
@CyberDem0n Thanks for the reply.  Problem with setting `tags.nofailover` to `false` or commented out results in that host at Site 2 to become a Leader and promotion of that PostgreSQL to master / read-write.  Desired result is all Site 2 databases be replicas with one (s84) streaming from Site 1 to reduce WAN traffic.  Site 1 sync(s81,s82,s83) -> Site 2 async(s84, s85) where s84 streams to s85.

Also, documentation for `tags.replicatefrom` says this:
> `replicatefrom: The IP address/hostname of another replica. Used to support cascading replication.`
Suggest updating the documentation to be more clear.  I've used Patroni many times over now and know only hosts actually work but took a shot with an IP. 

Patroni at Site 2 is there to send HTTP 200's to HAproxy when it is ready for read-only traffic (yes, `tags.noloadbalance` will be `false` when we are ready) and should Site 1 fail (hands waving in the air disaster!) then ready for manual promotion of one of those replicas.  If that is not possible from a Patroni standpoint then I'll disable Patroni and just configure PostgreSQL for streaming rep at Site 2.  We will lose the nice things Patroni does such as sync postgresql.conf but not the end of the world.

**Comment by gspiegelberg-pivotal** [comment]
@CyberDem0n Also, `standby_cluster` does not appear in the Site 2 `patronictl show-config` or fetching `/config` from DCS etcd.

**Comment by CyberDem0n** [comment]
> Also, documentation for tags.replicatefrom says this:

That's definitely an oversite and should be fixed.

> standby_cluster does not appear in the Site 2 patronictl show-config or fetching /config from DCS etcd.

Since there is no `standby_cluster` in the /config, Patroni doesn't count it as a standby, you have to create it using `patronictl edit-config`. It could happen in two cases, either stanby_cluster wasn't in the bootstrap.dcs when Patroni was started for the first time on the site2, or you did a basebackup manually from site1 and started Patroni with non-empty PGDATA, which contained patroni.dynamic.json.

**Comment by gspiegelberg-pivotal** [comment]
Okay, I added the following to Site 2 standby cluster patroni via `patronictl edit-config`:
```
standby_cluster:
  host: 10.10.1.83
  port: 6432
```
No slot named as desire is to stream from a Site 1 replica.

Streaming now which is good but problem remains that all databases at Site 2 want to stream from host at Site 1.  Preferred solution is one stream over the WAN to Site 2 and that recipient send to other hosts at Site 2.  How is that possible?

**Comment by CyberDem0n** [comment]
> ll databases at Site 2 want to stream from host at Site 1. Preferred solution is one stream over the WAN to Site 2 and that recipient send to other hosts at Site 2. How is that possible?

If everything is configured correctly it should not happen. Only the standby_leader streams from the site1 and remaining nodes should stream from the standby_leader.

**Comment by gspiegelberg-pivotal** [comment]
I figured it out after crawling the code.
